# Generated by Django 4.1 on 2022-09-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Upload_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
